#!/bin/sh
# Auto-login as admin
export XDG_RUNTIME_DIR=/run/user/1000
mkdir -p $XDG_RUNTIME_DIR
chown 1000:1000 $XDG_RUNTIME_DIR
chmod 700 $XDG_RUNTIME_DIR

# Auto start LabWC
exec /bin/su -l admin -c "labwc"
